In [5]:
aList = ["John", 33,"Toronto", True]

In [6]:
aList

['John', 33, 'Toronto', True]

In [7]:
type(aList)

list

In [8]:
bin_colors=['Red','Green','Blue','Yellow']

In [11]:
bin_colors=('Red','Green','Blue','Yellow')
print(f"The second element of the tuple is {bin_colors[1]}")

The second element of the tuple is Green


In [10]:
print(f"The elements after thrid element onwards are {bin_colors[2:]}")

The elements after thrid element onwards are ('Blue', 'Yellow')


In [12]:
nested_tuple = (1,2,(100,200,300),6)
print(f"The maximum value of the inner tuple {max(nested_tuple[2])}")

The maximum value of the inner tuple 300


In [13]:
bin_colors ={
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}

In [14]:
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [15]:
bin_colors.get("approved_color")

'Green'

In [16]:
bin_colors["approved_color"]

'Green'

In [17]:
bin_colors['approved_color']="purple"

In [18]:
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'purple', 'refused_color': 'Red'}


In [19]:
green = {"grass", 'leaves'}
print(green)

{'leaves', 'grass'}


In [20]:
yellow = {'dandelion', 'fire hydrant', 'leaves'}
red = {'fire hydrant', 'Blood', 'Rose', 'leaves'}

In [21]:
print(f"The union of yellow and red sets is {yellow|red}")

The union of yellow and red sets is {'Rose', 'fire hydrant', 'leaves', 'Blood', 'dandelion'}


In [22]:
print(f"The Intesaction of yellowand red it {yellow&red}")

The Intesaction of yellowand red it {'fire hydrant', 'leaves'}


In [5]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elene', 23, False],
    ['3', 'Steven', 40, True]])
df.columns = ['id', 'name', 'age', 'decision']
print(df)

  id    name  age  decision
0  1   Fares   32      True
1  2   Elene   23     False
2  3  Steven   40      True


In [7]:
df[['name', 'age']]

name  age
0   Fares   32
1   Elene   23
2  Steven   40

In [8]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [9]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elene   23     False
2  3  Steven   40      True

In [10]:
df[df.age>10]

id    name  age  decision
0  1   Fares   32      True
1  2   Elene   23     False
2  3  Steven   40      True

In [12]:
import numpy as np
myMatrix = np.array([[11,12,13],[21,22,23],[31,32,33]])

In [13]:
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [15]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [16]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])